---
dist: trusty

language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'

cache:
  pip: true
  directories:
    - eggs/

install:
  - pip install -r requirements.txt
  - buildout -c buildout-test.cfg

script: bin/test

notifications:
  email:
    on_success: never
    on_failure: never
